apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: greyvetro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-kube-ping
  namespace: greyvetro
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-kube-ping
  namespace: greyvetro
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: greyvetro
roleRef:
  kind: Role
  name: keycloak-kube-ping
  apiGroup: rbac.authorization.k8s.io
